api/urls.py
from django.urls import include, path

from tastypie.api import Api

from api.models import CategoryResource, CourseResource


api = Api(api_name='vs4')
api.register(CategoryResource())
api.register(CourseResource())

urlpatterns = [
    path('', include(api.urls), name='index'),
]

base/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('api/', include('api.urls')),
]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:course_id>/', views.single_course, name='single_course'),
]

api/models.py
from tastypie.authorization import Authorization
from tastypie.resources import ModelResource

from shop.models import Category, Course

from .authentication import CustomAuthentication


class CategoryResource(ModelResource):
    class Meta:
        queryset = Category.objects.all()
        resource_name = 'categories'
        allowed_methods = ('get',)


class CourseResource(ModelResource):
    class Meta:
        queryset = Course.objects.all()
        resource_name = 'courses'
        allowed_method = ('get', 'post', 'delete',)
        excludes = ('created_at', 'comments_qty',)
        authentication = CustomAuthentication()
        authorization = Authorization()

    def hydrate(self, bundle):
        bundle.obj.category_id = bundle.data['category_id']
        return super().hydrate(bundle)

    def dehydrate(self, bundle):
        bundle.data['category'] = bundle.obj.category
        return super().dehydrate(bundle)

    def dehydrate_title(self, bundle):
        return bundle.data['title'].lower()

    def dehydrate_price(self, bundle):
        return f'${bundle.data['price']}'

shop/models.py
from django.core.validators import MinValueValidator
from django.db import models
from django.utils import timezone


class Category(models.Model):
    title = models.CharField(
        max_length=255,
        verbose_name='Категория',
        help_text='Введите название категории'
        )
    created_at = models.DateTimeField(
        default=timezone.now,
        verbose_name='Создано',
        help_text='Дата и время создания'
        )

    class Meta:
        verbose_name = 'Категория курсов'
        verbose_name_plural = 'Категории курсов'
        ordering = ('title',)

    def __str__(self):
        return self.title


class Course(models.Model):
    title = models.CharField(
        max_length=255,
        verbose_name='Курс',
        help_text='Введите название курса'
        )
    price = models.FloatField(
        verbose_name='Цена',
        help_text='Введите цену курса',
        validators=[
            MinValueValidator(0.01)
        ]
    )
    students_qty = models.PositiveIntegerField(
        verbose_name='Количество учащихся',
        help_text='Введите количество стедентов на курсе',
        default=0,
    )
    comments_qty = models.PositiveIntegerField(
        verbose_name='Количество комментариев',
        help_text='Введите количество комментариев для курса',
        default=0
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        null=True,
        related_name='course_category',
        verbose_name='Категория',
        help_text='Выберите категорию курса'
        )
    created_at = models.DateTimeField(
        default=timezone.now,
        verbose_name='Создано',
        help_text='Дата и время создания'
        )

    class Meta:
        verbose_name = 'Учебный курс'
        verbose_name_plural = 'Учебные курсы'
        ordering = ('pk',)

    def __str__(self):
        return f'{self.title}'

shop/views.py
from django.shortcuts import get_object_or_404, render

from .models import Course

TEMPLATE_PREFIX = 'shop/'


def index(request):
    courses = Course.objects.all()
    return render(
        request,
        template_name=f'{TEMPLATE_PREFIX}courses.html',
        context={'courses': courses}
        )


def single_course(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    return render(
        request,
        template_name=f'{TEMPLATE_PREFIX}single_course.html',
        context={'course': course}
        )

templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    {% block head %}
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% endblock head %}
    <title>
      {% block title %}
      Document
      {% endblock title %}
    </title>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
      <div class="container">
        <a href={% url 'shop:index' %} class="navbar-brand">Cources shop</a>
        <span>
          <a href="/admin/" class="navbar-text me-3">Admin</a>
          <a href="/api/vs4/" class="navbar-text">API</a>
        </span>
      </div>
    </nav>
    <main class="container">
      {% block content %}
      {% endblock content %}
    </main>
  </body>
</html>

templates/shop/courses.html
{% extends 'base.html' %}
{% block title %}
  Все курсы
{% endblock title %}

{% block content %}
  <h1 class="h1">Курсы, доступные для покупки</h1>
  <table class="table table-sm table-bordered table-striped table-hover">
    <thead class="table-dark">
      <tr>
        <th><div class="d-flex justify-content-center">Title<div></th>
        <th><div class="d-flex justify-content-center">Category</div></th>
        <th><div class="d-flex justify-content-center">Price</div></th>
        <th><div class="d-flex justify-content-center">Students qty</div></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for course in courses %}
        <tr>
          <td><a href={% url 'shop:single_course' course.id %}>{{ course.title }}</a></td>
          <td>{{ course.category }}</td>
          <td><div class="d-flex justify-content-end">{{ course.price }}</div></td>
          <td><div class="d-flex justify-content-center">{{ course.students_qty }}</div></td>
          <td><div class="d-flex justify-content-center"><button class="btn btn-primary">Buy</button></div></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

templates/shop/single_course.html
{% extends 'base.html' %}
{% block title %}
    Курс {{ course.title }}
{% endblock title %}
{% block content %}
    <h1 class="mt-5">Курс  {{ course.title }}</h1><br>
    <h2>Категория: {{ course.category }}</h2><hr>
    Цена: {{ course.price }}<br><hr>
    Кол-во участников: {{ course.students_qty }}<br><hr>
    Количество комментариев: {{ course.comments_qty}}<br><hr>
{% endblock content %}